version: '3'

services:
  collector:
    build: ./collector
    environment:
      - CONFIG_PATH=/app/config/settings.yaml
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=plc_monitor
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DEVICES_CONFIG_PATH=/app/config/devices.yaml
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    depends_on:
      - database

  backend:
    build: ./backend
    environment:
      - CONFIG_PATH=/app/config/settings.yaml
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=plc_monitor
      - DB_USER=admin
      - DB_PASSWORD=secret
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: plc_monitor
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
